### ISSUE TITLE
parsers not in list

### ISSUE THREAD

**Issue by dzdash** [Defense-Cyber-Crime-Center/DC3-MWCP#6]
When adding a new parser to the `mwcp/parsers` directory, and then attempting to run the `mwcp-tool.py -l` command, the new parser does not appear in the list, nor does it compile. 

Additionally, when trying to run the parser using the `-p` option, mwcp indicates the parser does not exist.

However, when then trying to reference the parser by specifying the parser directory, using the `--parserdir` option, mwcp can run the parser successfully.

**Comment by DC3-DCCI** [comment]
Thank you for the bug report.

It looks like your parser wasn't getting registered because the framework was only accounting for parsers installed using setuptool’s entry_points for the default directory.

This should be fixed in version 1.4.1, which was just released.  Please let us know if this resolved your issue or if it’s still present.  If you don’t respond within one week that this is still a problem this issue will be closed.
